runtime: python27
api_version: 1
threadsafe: true

handlers:
# Route localhost:8080/static_files/* to static_files/ folder.
- url: /static
  static_dir: static

# Route localhost:8080* (everything else) to 'app' in main.py.
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
